### ISSUE TITLE
Start using pull request workflow

### ISSUE THREAD

**Issue by nejch** [siemens/continuous-clearing#1]
Hey folks, if you have several people in the team, please consider protecting your main branch and use PRs and reviews.

https://github.com/siemens/continuous-clearing/commits/main

/cc @ThomasPiskol @Vijayalakshmi027 @karthika-g

**Comment by Vijayalakshmi027** [comment]
Hi @nejch ,
Sure,  we make use of pull request  & review and will protect the main branch as suggested.
Thank you

**Comment by nejch** [comment]
I guess you've started as I see `main` is protected now and you had your first PR :) thanks for keeping it clean and happy coding.
