### ISSUE TITLE
Unable to use self-hosted runner.

### ISSUE THREAD

**Issue by prasenjeetnath** [siemens/continuous-clearing#157]
Hi Team,
The self-hosted agents are showing disabled in runner (Self-hosted runners were disabled by your organization admin.). Can you please enable it?
![github runner](https://github.com/siemens/continuous-clearing/assets/147582543/f5f44cb1-9742-4d0d-8898-7bbcb199ad0f)

**Comment by prasenjeetnath** [comment]
Hi team,
Could you please update as as we are unable to work because of this

**Comment by prethyushp** [comment]
This issue has been fixed.
