### ISSUE TITLE
Failed to connect SW360 in Docker run

### ISSUE THREAD

**Issue by sumanthkb44** [siemens/continuous-clearing#16]
Unable to connect SW360 instance in PackageIdentifier, while executing CATool as docker container,
![image](https://user-images.githubusercontent.com/84563853/225860885-b0779903-f5a6-44bb-8d60-e64f55384f0c.png)

**Comment by karthika-g** [comment]
Hi Sumanth,
Check the Sw360 is reachable or not.
If yes, add `--add-host hostname:IPAddress` in docker run. it will add new entry in hosts file inside container.

**Comment by sumanthkb44** [comment]
Issue resolved thanks.
