### ISSUE TITLE
All the components are getting treated as Dev dependency (Poetry).

### ISSUE THREAD

**Issue by NihalBarick** [siemens/continuous-clearing#191]
We have multiple Python projects which is using Poetry for dependency management. All the packages in our application are main dependencies, but when we are running the continuous clearing tool all the components are considered as dev dependencies.

We are using latest version of CA tool: 6.2.2

We are using latest version of poetry: 1.8.3

We are using latest version of python: 3.12 and also sometimes 3.11, 3.10 (Since we are having multiple python projects)

**Comment by sumanthkb44** [comment]
Hi Nihal,

Can you share the sample **Poety.lock** (v1.8.3) file you're using.
And also let us know how the dependencies been categorized in the **pyproject.toml** file for Main dependencies.

**Comment by sumanthkb44** [comment]
This will get fix with upcoming release of Clearing Tool.
Corresponding PR : https://github.com/siemens/continuous-clearing/pull/209
