### ISSUE TITLE
SW360.'Source Code Download URL' for Debian packages should be the dsc file

### ISSUE THREAD

**Issue by ericbl** [siemens/continuous-clearing#208]
For Debian packages, the tool seems to set the .orig.tar.gz file into the 'Source Code Download URL' field of SW360.

It should be the 'dsc' file.

Let's take an example (Siemens internal):
https://sw360.siemens.com/group/guest/components/-/component/release/detailRelease/1fa4ed40b7e94fd2a5ffbd778499ca99#/tab-Summary
refers to the libssh2 package. According to the author of that release, your tool was used in their workflow to create or upload the component on sw360.
You see the [orig.tar.gz](https://snapshot.debian.org/archive/debian-debug/20201207T025837Z/pool/main/libs/libssh2/libssh2_1.9.0.orig.tar.gz) set at 'Source Code Download URL'

The proper source file for that package is the [corresponding dsc](https://deb.debian.org/debian/pool/main/libs/libssh2/libssh2_1.9.0-2+deb11u1.dsc)
Setting the dsc is what [Gernot's tool](https://code.siemens.com/linux/distro-clearing/debian) is doing.

Please adapt your tool to set the dsc file and NOT the orig.tar.gz here.

Generally speaking, cross testing should be done between tools to ensure they set the same data.
See with Gernot for Debian specific topic, i.e. for Debian packages.

**Comment by gernot-h** [comment]
Not sure if it's obvious which "Gernot" is meant, so in case of questions, feel free to contact me here or via Siemens channels. ;-)

**Comment by sumanthkb44** [comment]
@ericbl Thanks for the issue.

Will check with the Clearing team (@WagnerMarco ) and will adopt the changes accordingly.

**Comment by sumanthkb44** [comment]
@ericbl Thanks for the suggestions,

We had a discussion with @WagnerMarco & @gernot-h 
Will try to incorporate this in our feature release.
