### ISSUE TITLE
update nuget packages accross projects

### ISSUE THREAD

**Issue by ericbl** [siemens/continuous-clearing#22]
in the vs solution, some projects are using nuget packages meant for .NET 3.1. other for 6.0 or even 7.0
consolidate the packages to target .NET 6.0 as the output of your app.

**Comment by karthika-g** [comment]
Could you confirm if you are referring to these

![image](https://user-images.githubusercontent.com/40568919/227859931-b5fda656-c1b5-4e8c-8752-c90cbcebd72d.png)

**Comment by karthika-g** [comment]
Packages are updated and Released in V3.1.0
