### ISSUE TITLE
update .net runtime in Dockerfile

### ISSUE THREAD

**Issue by ericbl** [siemens/continuous-clearing#23]
https://github.com/siemens/continuous-clearing/blob/main/Dockerfile#L5
FROM mcr.microsoft.com/dotnet/runtime:6.0.7-bullseye-slim-amd64

why using a specific (and now outdated) version ?

https://hub.docker.com/_/microsoft-dotnet-runtime/?tab=description
shared tag for 
6.0.15-bullseye-slim-amd64, 6.0-bullseye-slim-amd64, 6.0.15-bullseye-slim, 6.0-bullseye-slim, 6.0.15, 6.0

-> use 6.0 or 6.0-bullseye-slim for more flexibility

**Comment by sumanthkb44** [comment]
From the next release onwards we will be updating the package with the latest version of Dotnet runtime available.

**Comment by karthika-g** [comment]
Packages are now updated in latest release V3.1.0.Closing this Issue
